export const ADD_COMMENT = 'ADD_COMMENT';
export const DISHES_LOADING = 'DISHES_LOADING'; //люда закгружаются (возможно с сервера)
export const DISHES_FAILED = 'DISHES_FAILED';//блюда не удалось загрузить
export const ADD_DISHES = 'ADD_DISHES'; // добавть блюда в стор
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';
